# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74c405511a7a594610c4f082c2cd1fce2d63f0b8f59f351d1e0f307f0b328eb6c634605f6eb944fc6ae4ad967dc675ed8792abfb492e7cc53b858eac360e6d42

test:
  secret_key_base: 38e0d1e7efcd31d2055872d4aef181a4a1876b498b36db57b12bda44c1a9878397020102a57955a0bb5d7dd0ac8cd6bab0b11c006faf52c8ec5fa5d3196d5872

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
